services:
  zunda:
    hostname: zunda
    network_mode: host
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      network: host
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USERNAME: ${USERNAME:-user}
        GROUPNAME: ${GROUPNAME:-user}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NUMBA_CACHE_DIR=/tmp
      - WANDB_API_KEY=${WANDB_API_KEY:-}
      - WANDB_MODE=${WANDB_MODE:-online}
      - DOCKER_CONTAINER=true
    volumes:
      - ../:/ws
      - /tmp/.X11-unix:/tmp/.X11-unix
    shm_size: 64gb
    runtime: nvidia
    tty: true
    stdin_open: true
